version: '3'
services:
  mysql: 
    image: arm64v8/mysql:8.0.32-oracle
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: courses
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"