POST http://localhost:3000/products 
Content-Type: application/json

{
  "name": "My Product",
  "price": 100
}

###
GET http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODA1NjkzMjAsInN1YiI6ImRjZDQ1YjUzLWU3MmUtNGQ0Yi05ODE0LWMzZDBhNDYzZjY2ZiJ9.IjubcIii9M0MeYaARIQbNbqhL_xEhUns_f1xRoZo5hg

###

GET http://localhost:3000/products/a983cb7a-2891-49c0-91d0-47dfa43e3b10

###

PUT http://localhost:3000/products/a983cb7a-2891-49c0-91d0-47dfa43e3b10
Content-Type: application/json

{
  "name": "My Product Updated",
  "price": 200
}

###

DELETE http://localhost:3000/products/a983cb7a-2891-49c0-91d0-47dfa43e3b10