POST http://localhost:3000/products 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODA2MjA0NTQsInN1YiI6ImYzY2NjN2YzLWFmNzItNGUzYS04ODU4LWEyMmMwZGQ1NDM4OSJ9.puswoIKi04Kp6P62RvGf8nULL8ED7SP0E2_7CIpCcPw

{
  "name": "My Product",
  "price": 100
}

###
GET http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODA2MjA0NTQsInN1YiI6ImYzY2NjN2YzLWFmNzItNGUzYS04ODU4LWEyMmMwZGQ1NDM4OSJ9.puswoIKi04Kp6P62RvGf8nULL8ED7SP0E2_7CIpCcPw

###

GET http://localhost:3000/products/a983cb7a-2891-49c0-91d0-47dfa43e3b10

###

PUT http://localhost:3000/products/a983cb7a-2891-49c0-91d0-47dfa43e3b10
Content-Type: application/json

{
  "name": "My Product Updated",
  "price": 200
}

###

DELETE http://localhost:3000/products/a983cb7a-2891-49c0-91d0-47dfa43e3b10