POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "jd@teste.com.br",
    "password": "123456"
}

###
POST http://localhost:3000/users/generate_token HTTP/1.1
Content-Type: application/json

{
    "email": "jd@teste.com.br",
    "password": "123456"
}